### ISSUE TITLE
New kafka reader

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice_kafka_reader#1]
This will be a new implementation of a kafka reader based around the node-rdkafka library https://github.com/Blizzard/node-rdkafka from Blizzard.

The model shouldn't be fundamentally different from the old reader.
 * Reader is setup with the topic and number of partitions
 * The slicer hands out topic partition assignments to workers
 * The worker will read a slice of data from the assigned partition and process it.
 * Only one worker can be reading from a partition at any time
 * The number of usable workers may be limited by the number of available partitions.
 * The tricky part will be at what point the slice is considered complete and the offset into the partition gets moved.
     * If it gets moved early then another worked could read from that offset and begin processing.
     * But if the current slice fails then the offset will have moved and data would be lost.
         * In most instances these jobs will be deployed as persistent jobs so recovery of slices won't be an option.
     * Late moving of the offset will require a separate processor that would be added to the end of the job.
          * This may also imply there is state shared from the reader through to that processor which may be tricky.

**Comment by godber** [comment]
Is the structure of the old reader still valid? https://github.com/terascope/teraslice-kafka

**Comment by kstaken** [comment]
It will end up being fairly similar although there are some details around the way the rdkafka library works with consumers which may actually eliminate the need for the slicer to allocate partitions. Kafka overall has gotten much better around the idea of consumer groups and balancing partitions across them.

**Comment by kstaken** [comment]
Initial implementation is complete. Closing.
